### ISSUE TITLE
Tag pro

### ISSUE THREAD

**Issue by hayyaun** [tarlaun/tarlaun#1]
@tarlaun میتونم بدونم چجوری از ایران گیت هاب پرو گرفتین مرسی

**Comment by tarlaun** [comment]
سلام،[ این لینک](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/use-github-for-your-schoolwork/apply-for-a-student-developer-pack) توضیح داده.

**Comment by hayyaun** [comment]
ممنون من یبار اینکارو کردم ولی ظاهرا مدارکم رو بخاطر کشورم قبول نکردن
